name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "0 */3 * * *"   # runs every 3 hours
  workflow_dispatch:        # allows manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -L -X GET "https://enprom-gmbh-financial.streamlit.app/"
